name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
prerelease: false

version-resolver:
  major:
    labels: ['breaking']
  minor:
    labels: ['feature']
  patch:
    labels: ['bug', 'refactor', 'tests', 'ci', 'dependencies', 'assets', 'docs', 'backend', 'ui']
  default: patch

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: $PREVIOUS_TAG...v$RESOLVED_VERSION
